### ISSUE TITLE
Use Zen Browser as a more cutting-edge base for a “Next” version of Cachy Browser

### ISSUE THREAD

**Issue by extropyst** [CachyOS/CachyOS-Browser-Settings#14]
Consider building on [Zen Browser](https://www.zen-browser.app/) as the base for a "Next" version of Cachy Browser, which will allow for a more modern experience with features that enable better productivity. 

(And collaborating now at an early stage with the developers of that browser will allow you to mutually empower each other by creating a closer relationship.)

I attach the [repository on Git-Hub](https://github.com/zen-browser/desktop) where you can review. The developers are more actively in their [Discord group](https://discord.gg/nnShMQzR4b).

**Comment by vnepogodin** [comment]
unlikely

**Comment by 1Naim** [comment]
To elaborate, the goals of zen browser and cachyos browser differ whereas zen browser is focused at performance, cachyos browser is more oriented towards privacy and security. Zen Browser is also currently at alpha stage, so there won't be any short-term plans of using zen browser as a base for now.

**Comment by ptr1337** [comment]
> Consider building on [Zen Browser](https://www.zen-browser.app/) as the base for a "Next" version of Cachy Browser, which will allow for a more modern experience with features that enable better productivity.
> 
> (And collaborating now at an early stage with the developers of that browser will allow you to mutually empower each other by creating a closer relationship.)
> 
> I attach the [repository on Git-Hub](https://github.com/zen-browser/desktop) where you can review. The developers are more actively in their [Discord group](https://discord.gg/nnShMQzR4b).

Zen does also only follow the upstream release cycle, as cachy-browser does. Besides its "theming" and config, there is no difference.
The zen browser can be found in our repository.
