### ISSUE TITLE
some websites dont match theme

### ISSUE THREAD

**Issue by baturax** [CachyOS/CachyOS-Browser-Settings#18]
i started to use cachy browser today and it is good. but some apps like github, google dont match theme. for instance the theme i use rn is dark even though cachy uses dark, websites dont. i installed firefox if it is only with cachy and it looks so. same websites: first one firefox, second is cachy 
![image](https://github.com/user-attachments/assets/4c423160-12a1-4db7-a88f-46cc9551e1af)
![image](https://github.com/user-attachments/assets/f228319e-3dda-4d41-94e4-4c1492c6d22b)

**Comment by Shendisx** [comment]
There is already a fix mentioned in our wiki about this issue.

It comes from `privacy.resistFingerprinting` , you'll have to disable it.

**Comment by baturax** [comment]
thanks
