### ISSUE TITLE
Prefer usability when it comes to videocalls and content

### ISSUE THREAD

**Issue by federicotorrielli** [CachyOS/CachyOS-Browser-Settings#3]
Hello there,

I've been testing out the browser configuration provided by the chachy repository, and I'm generally very impressed. However, I'd like to raise an issue regarding media functionality and videocalls.

Currently, the Widevine, H264, and DRM components are blocked by default, which makes the configuration a bit challenging to use for tasks involving multimedia. While I understand that these settings can be enabled manually, I believe this may pose a significant hurdle to new users who are unfamiliar with these configurations.

From a privacy standpoint, having CanvasBlocker by default is a fantastic move, and it's one of the features that really drew me to this configuration. But having the H264 decoding disabled by default renders the setup unsuitable for work-related activities, especially in this era of remote work and videocalls.

To strike a balance between privacy and usability, I propose enabling Widevine, H264, and DRM by default. This change could make this custom config more user-friendly right out of the box, while still maintaining a high level of privacy and security.

Moreover, considering the widespread use of ad-blocking extensions, integrating uBlock Origin by default might also be a beneficial addition to enhance users' browsing experience.

Thanks for your time and consideration. I hope these suggestions contribute to making the chachy config even better. Looking forward to hearing your thoughts on this.

**Comment by ptr1337** [comment]
> @ptr1337 updates on this?

Hi,

Feel free to do an PR if you want to the settings. Then I will do a recompile.
I can do it also later when I come home from work
