### ISSUE TITLE
BUG: "Enable DNS over HTTPS" does not stick on OFF. It always reverts back to the default Max when restarting the browser.

### ISSUE THREAD

**Issue by Mangoes** [CachyOS/CachyOS-Browser-Settings#8]
Hi,

"Enable DNS over HTTPS" in the settings does not stick on OFF (in about:preferences#privacy). It always reverts back to the default Max when restarting the browser.

Could you please fix this?

Many thanks.

**Comment by vnepogodin** [comment]
Hi @Mangoes 

this is happening because we use `pref` instead of `defaultPref``. we want DoH do be enabled by default.
for some reason when we use `defaultPref` the DoH isn't going to be enabled by default then

**Comment by Mangoes** [comment]
Ok, but the problem is i.ex when you are on a network that is already secured by a vpn with a great filtering DNS inside the vpn network. In this case using another DNS in the browser is a downgrade.

So, it's just cumbersome to always disable this every time cachy-browser is started.

Anyway, I'm sure you'll make the best choices possible with what you are dealing with, so I'll let you see how you can fix this if possible.

Thanks!

**Comment by ShayBox** [comment]
DoH also prevents my VPN extension from working (Windscribe)

**Comment by Vinfall** [comment]
You can try add this to `~/.cachy/cachy.overrides.cfg` or wherever appropriate so DoH is always disabled and cannot be turned on unless you remove it from overrides:

```js
// Disable DoH
lockPref("network.trr.mode", 5);
```

But do make sure your other DNS is indeed secure and does not leak in the first place.

**Comment by vnepogodin** [comment]
fixed in https://github.com/CachyOS/CachyOS-Browser-Settings/commit/35fa2bbb337336a918df82a35ebd9a50e1718821 and https://github.com/CachyOS/CachyOS-Browser-Settings/commit/69eb56c9edc827d55ef12abf36fd2313aaa65a0c
