### ISSUE TITLE
Flatpak please?

### ISSUE THREAD

**Issue by RasheedAZ** [CachyOS/CachyOS-Browser-Settings#9]
Hi. I just stumbled upon CachyOS recently and appreciate you guys making your own browser based on Firefox with private defaults and a non-Big Tech search engine at least.

Can you please package it as a Flatpak and get it listed and verified on Flathub so people on other distros can also use it.

Thanks :)

**Comment by Elyas2024** [comment]
please :)

**Comment by 1Naim** [comment]
Our browser is heavily based on [Librewolf](https://librewolf.net). Consider using the [LibreWolf Flatpak](https://flathub.org/apps/io.gitlab.librewolf-community) instead as it is very unlikely that we will package cachy-browser as a flatpak.
